# Generated by Django 4.1.7 on 2023-06-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=25)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_age', models.IntegerField()),
                ('stu_gender', models.CharField(max_length=25)),
            ],
        ),
    ]
